# Generated by Django 3.0.3 on 2020-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0002_auto_20200305_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
