# Generated by Django 3.0.3 on 2020-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0003_auto_20200307_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
