# Generated by Django 3.0.3 on 2020-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0003_auto_20200208_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
